# 配置参考 https://segmentfault.com/a/1190000020340570
version: '3'
services:

  # 后端服务
  service-park:
    container_name: service-park
    image: ${DOCKER_IMAGE_TAG}
    restart: always
    networks:
      - park-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.service-park.entrypoints=websecure"
      - "traefik.http.routers.service-park.rule=Host(`park.matrix-net.tech`) && PathPrefix(`/park`)"
      - "traefik.http.middlewares.park-stripprefix.stripprefix.prefixes=/park"
      - "traefik.http.routers.park.middlewares=park-stripprefix"
      - "traefik.http.routers.service-park.tls.certresolver=aliyunresolver"
      - "traefik.http.services.service-park.loadbalancer.server.port=8000"
    ports:
      - "8000:8000"

networks:
  park-network:
    driver: bridge
    name: park-network
