swagger: "2.0"
info:
  title: 接口文档
  description: |
    系统服务端接口文档
  version: 1.0.0
basePath: /park/v1
paths:
  /user/:
    get:
      tags:
      - user
      summary: 查询用户
      description: |-
        查询用户 http://127.0.0.1:8080/park/v1/user
        <br>
      operationId: UserController.查询用户
      parameters:
      - in: query
        name: query
        description: 查询参数，用&分隔
        type: string
      - in: query
        name: sortby
        description: 排序
        type: string
      - in: query
        name: order
        description: 升序asc，降序desc
        type: string
      - in: query
        name: limit
        description: 限制个数，默认10
        type: string
      - in: query
        name: offset
        description: 偏移，默认0
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.ResponseData'
    post:
      tags:
      - user
      summary: 绑定用户
      description: |-
        绑定用户
        <br>
      operationId: UserController.Post
      parameters:
      - in: body
        name: body
        description: 用户结构体
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.ResponseData'
    delete:
      tags:
      - user
      summary: 批量删除用户
      description: |-
        create User
        <br>
      operationId: UserController.批量删除用户
      parameters:
      - in: body
        name: body
        description: 只填id字段即可
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/models.User'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/controllers.ResponseData'
        "403":
          description: body is empty
  /user/{id}:
    get:
      tags:
      - user
      summary: 获取用户
      description: |-
        获取用户根据ID
        <br>
      operationId: UserController.Get
      parameters:
      - in: path
        name: id
        description: 用户ID
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.ResponseData'
    put:
      tags:
      - user
      summary: 更新用户
      description: |-
        更新用户
        <br>
      operationId: UserController.更新用户
      parameters:
      - in: path
        name: id
        description: 用户ID
        required: true
        type: string
      - in: body
        name: body
        description: 用户结构体内容
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.ResponseData'
    delete:
      tags:
      - user
      summary: 删除用户
      description: |-
        删除用户
        <br>
      operationId: UserController.删除用户
      parameters:
      - in: path
        name: id
        description: 删除用户的ID
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.ResponseData'
  /user/test:
    get:
      tags:
      - user
      summary: 测试
      description: |-
        测试
        <br>
      operationId: UserController.Get
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.ResponseData'
  /websocket/information:
    get:
      tags:
      - websocket
      summary: 数据
      description: |-
        通过websocket推送数据
        <br>
      operationId: WebSocketController.Information
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Information'
  /websocket/logcat:
    get:
      tags:
      - websocket
      summary: 日志
      description: |-
        通过websocket推送日志
        <br>
      operationId: WebSocketController.Logcat
      responses:
        "200":
          description: '{string}'
definitions:
  controllers.ResponseData:
    title: ResponseData
    type: object
    properties:
      data:
        $ref: '#/definitions/controllers.interface'
        description: 数据
      message:
        description: 附加信息
        type: string
      status:
        description: 状态 1:成功,-1:失败
        type: integer
        format: int64
  controllers.interface:
    title: interface
    type: object
  models.Information:
    title: Information
    type: object
    properties:
      data:
        $ref: '#/definitions/models.interface'
      message:
        description: 信息
        type: string
      type:
        description: 数据类型
        type: integer
        format: int64
  models.User:
    title: User
    type: object
    properties:
      address:
        description: 钱包地址
        type: string
      content:
        description: 介绍
        type: string
      create_time:
        type: string
        format: datetime
      email:
        description: 邮件
        type: string
      id:
        type: integer
        format: int64
      name:
        description: 名称昵称
        type: string
      number:
        description: 号码
        type: string
      remarks:
        description: 备注
        type: string
      status:
        description: 上线下线 0:离线 1:在线
        type: integer
        format: int32
      update_time:
        type: string
        format: datetime
  models.interface:
    title: interface
    type: object
tags:
- name: websocket
  description: |
    WebSocketController handles WebSocket requests.
